# development environment for jupysql-plugin
name: jupysql-plugin

channels:
  - conda-forge

dependencies:
  - nodejs=16
  - jupyterlab<4 # this will install jlpm
  - pip
  - pip:
    - build
    - twine
    - hatch
