name: CI

on:
  push:
    branches:
      - main
      - 'dev/**'
  pull_request:



jobs:
  Jest:
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3


      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.3.1-0'
          environment-file: environment.dev.yml
          init-shell: >-
            bash
          cache-environment: true

      - name: Lint
        run: |

          python -m pip install --upgrade pip pkgmt
          pkgmt lint

      - name: Install dependencies
        run: |

          pip install .
          # check package is importable
          python -c "import jupysql_plugin"

      - name: Test
        run: | 

          jlpm install
          jlpm test

      - name: Visual tests
        run: | 

          cd ui-tests
          jlpm install
          jlpm playwright install
          jlpm test